const Router = require("express")
const router = new Router()
const userController = require("../controllers/userController")
const authMiddleware = require("../middleware/authMiddleware")
const checkRole = require("../middleware/checkRoleMiddleware")
const basketCheck = require("../middleware/checkBasketOwnerMiddleware")

router.post("/registration", userController.registration)
router.post("/login", userController.login)
router.post("/basket/:deviceId", authMiddleware, userController.createBasket)
router.post("/rating/:deviceId", authMiddleware, userController.setRating)
router.delete("/basket/:userId", authMiddleware, basketCheck, userController.clearBasket)
router.delete("/basket/item/:deviceId", authMiddleware, userController.deleteOneBasketItem)
router.delete("/rating/:deviceId", authMiddleware, userController.deleteRating)
router.get("/basket/:userId", authMiddleware, basketCheck, userController.openBasket)
router.get("/auth", authMiddleware, userController.check)
router.get("/", userController.getAll)
router.get("/rating", userController.rt)

module.exports = router